### ISSUE TITLE
How to use it properly?

### ISSUE THREAD

**Issue by hrqmonteiro** [wacossusca34/glava#51] opened 2018-07-11 09:18 UTC
All i can do is open a terminal and type "glava" and it appears as pre-configured (the bar style and windowed, etc)

I mean, how do i create my own module? The wiki is so confusing. I have to create a folder in the config file and name it wharever i want (lets say i create one named 'hrq'), and then inside the folder i put a 1.frag file and a config file?

I tried to create a config file and run glava by typing: glava -e /pathtomyfile.glsl, but NO MATTER HOW I WRITE IT, it shows an error like this: No module was selected, edit 'hrq' to load a module with `#request mod [name]. No matter what i do, this error shows up.

All i wanted to do is to edit this glava to use it properly, but among all things i saw this week, this wiki was the only one i couldnt figure how to configure

**Comment by Aaahh** [comment] 2018-07-11 15:04
edit the ./config/glava/rc.glsl
make a duplicate of the bars/ and bars.* and then just edit those. 
set it in the rc.glsl

**Comment by wacossusca34** [comment] 2018-07-13 01:05
I can try to clarify further in the documentation, but I'm not completely sure what is confusing you. The error message is actually quite clear in the sense that you literally need to create and select a proper module (see wiki on [writing your own modules](https://github.com/wacossusca34/glava/wiki#writing-your-own-modules)), not just a single file. The entry point just needs to specify the name of the module via `#request mod <name>`.

If you read the source, the 'entry point' is akin to `rc.glsl` in which it sets up initial options for the renderer _before it has been instantiated_. Options set within the module (and any includes from that point) are done with an active OpenGL context. This separation exists for some technical reasons (X11 window creation and hints) and also allows changing modules at runtime if I wish to change the code to allow that.

As @Aaahh said, it's best to use the existing examples since there's some boilerplate involved with making a visualizer.

**Closed** 2018-07-26 03:29 UTC

**Comment by Keeermalec** [comment] 2020-12-28 21:18
OK, so I can visualize bars, radial, graph, wave or circle

It seems very feature-pure for an audio visualizer

Are there more complex examples?
