### ISSUE TITLE
Circle module on deepin 15.9 don't work correctly

### ISSUE THREAD

**Issue by banancc** [wacossusca34/glava#107] opened 2019-03-12 16:00 UTC
I installed glava as it shown there : [https://www.linuxuprising.com/2018/11/embed-audio-visualizer-on-your-linux.html](url)
When i set `#request mod circle
` in rc.glsl happened this : 
![DeepinScreenshot_20190312175146](https://user-images.githubusercontent.com/47900972/54215443-98ecb400-44f0-11e9-9463-1daa38b57a3e.png)
Please help! Thanks!

**Comment by coderobe** [comment] 2019-03-12 16:28
Should be fixed with #106

**Comment by coderobe** [comment] 2019-03-12 16:28
Duplicate of #105

**Comment by wacossusca34** [comment] 2019-03-12 18:36
#106 is merged

**Closed by wacossusca34** 2019-03-12 18:36 UTC
Labels: bug, duplicate

**Comment by banancc** [comment] 2019-03-12 18:52
> Should be fixed with #106

i copyed script from there and pasted it in my files, restarted glava and nothing changed :(

**Comment by coderobe** [comment] 2019-03-12 19:07
Try with completely fresh config files from the current master branch
