### ISSUE TITLE
Use Xdefaults for colours

### ISSUE THREAD

**Issue by Amolith** [wacossusca34/glava#77] opened 2018-11-12 18:45 UTC
I'd love the ability to use Xdefaults colours for glava. `wal` themes my whole system and an easy way to make it theme applications is by giving them an Xdefaults variable that changes every time I run `wal`.

I know I can use more neutral colours but it would look a lot better if it used the same colours as everything else. This looks really good but the blue doesn't _quite_ fit.

![image](https://user-images.githubusercontent.com/29460675/48368145-eb23e280-e680-11e8-8bf2-340e956ef210.png)

**Comment by wacossusca34** [comment] 2018-11-13 02:30
There's some problems with adding complete support to read from `.Xdefaults`:

* GLava's rendering itself has nothing to do with X11 and is ill-suited for configuration via XResources.
* The code for this will be convoluted. I would need to add support using `XrmDatabase`, but it would need to be optional since I am trying to leave proper Wayland support on the table for now. I would also be mapping a named X11 color to OpenGL by _emitting a macro in the shader_. At that point it just makes more sense to edit the configuration files provided.
* **There is no notion of a uniform color for GLava itself.** That is the responsibility of the shader(s) in question, which don't even have to use a single color (ie. they are free to _compute_ colors as part of the visualization).

Ultimately whats needs to happen for GLava to play nicely with your workflow is that all the shaders need to conform to some standard practice for using color definitions, where `graph.glsl` would have a `COLOR` definition simply set to `DEFAULT_COLOR` defined in `rc.glsl` (or a separate global file). From there I can work with adding support to map those defaults to named X11 colors.

Honestly I'm not sure if doing so is a good idea; as I mentioned earlier shaders are currently free to compute colors, having global color definitions and usage (aka themes) conflicts with effects like rendering colors based on the frequency response (amplitude).

At the moment you can obviously go into `bars.glsl` and edit the `COLOR` definition to whatever color you like (it defaults to a subtle blue-white gradient).

**Comment by wacossusca34** [comment] 2018-11-13 02:36
I will leave this issue open for discussion if someone feels like they can suggest a better approach, or if others want to chime in for theme support.

**Comment by QuentinI** [comment] 2019-03-09 15:20
Maybe a bit off topic, but I didn't want to open a new issue just to ask a newbie question and this one seems to be somewhat related.
Is there any way to pass arbitrary data to shaders in runtime? My use case is changing the shader color on the fly to match the color of currently playing album.
I currently change the shader code itself and then try to restart glava in-place, but it looks a bit messy and it's hard to ensure the new glava window will end up in the needed place.

**Comment by wacossusca34** [comment] 2019-03-09 18:31
@QuentinI not at the moment, but it would be fairly trivial to add support for something like that (ie. accept arbitrary value(s) from pipe/file.

**Comment by QuentinI** [comment] 2019-03-10 13:19
@wacossusca34 that would be a nice feature to have IMHO, and it would provide a workaround for this issue via fairly trivial shader customization.

**Comment by wacossusca34** [comment] 2019-03-10 19:02
@QuentinI I will try to add this today.

**Comment by wacossusca34** [comment] 2019-03-10 23:20
@QuentinI pull from `master` and try the new `--stdin`/`-i` flag:

```
-i, --stdin[=FORMAT]    specifies a format for input to be read from stdin. The input
                           may be read from the STDIN macro from within shader sources.
                           A stream of inputs (each overriding the previous) must be
                           separated by newline ('\n') characters.
[...]
The FORMAT argument must be a valid GLSL type. If `--stdin` is used without an argument,
the default type is `vec4` (type used for RGBA colors)
```

Vector types may be specified with comma-separated floating point values (ie. `0.5,0.1,0.5,1`), or in the case of `vec4`, hexadecimal color syntax may also be used (ie. `#55AE55FF`). If you omit the final alpha channel with the hex format, it will default to `FF` (`1.0`).

To make use of this feature, you need to use the `STDIN` binding within your configuration, ie. in `bars.glsl`:

```GLSL
#define COLOR STDIN
```

Each value overrides the previous set, so you can effectively stream simple datatypes to GLava now.

**Comment by wacossusca34** [comment] 2019-03-10 23:25
Also, another macro `USE_STDIN` is exposed for those who want to configure GLava to more intelligently handle the `-i` flag:

```GLSL
#if USE_STDIN == 1
#define COLOR STDIN
#else
#define COLOR #FF0000
#endif
```

**Comment by wacossusca34** [comment] 2019-03-10 23:37
The above commit just fixed this feature so it works with pipes, so make sure you are on `c9dac68` or later.

**Comment by QuentinI** [comment] 2019-03-11 10:59
@wacossusca34 this is totally dope, many thanks. I'll check it out ASAP.

**Comment by wacossusca34** [comment] 2019-03-12 00:59
@QuentinI I may further expand on this by allowing multiple bindings to be specified at startup, specified through `binding:value` syntax in stdin.

It's worth mentioning this evaluates to a uniform in a shader, and thus can only be used with defines. You cannot use this feature with requests as they are evaluated during compile-time.

**Comment by coderobe** [comment] 2019-03-12 14:07
This appears to be an issue with the `circle` shader exclusively, as i cannot reproduce it with different shaders:

![image](https://user-images.githubusercontent.com/8442384/54205880-80bc6b00-44d7-11e9-9db1-f672749ce0cf.png)

![image](https://user-images.githubusercontent.com/8442384/54206001-c11be900-44d7-11e9-9ba9-7ba3bda2b011.png)

(ignore the fuzz in the circle screenshot, that's a different bug :wink:)

**Comment by QuentinI** [comment] 2019-03-12 14:36
@coderobe actually, `bars` is also affected, though in somewhat different fashion:
```glsl
// ...
/* Bar color */
#if USE_STDIN == 1
#define COLOR STDIN
#else
#define COLOR #FF0000
#endif
// ...
```
No piping:
![2019-03-12_17:25:50](https://user-images.githubusercontent.com/18196237/54208102-6771e980-44ec-11e9-9a30-64e2a03d566d.png)
With piping. Note that bars are not completely opaque:
![2019-03-12_17:27:00](https://user-images.githubusercontent.com/18196237/54208251-9ab47880-44ec-11e9-9789-94340fc4187e.png)
Specifying alpha channel does not exactly help:
![2019-03-12_17:26:36](https://user-images.githubusercontent.com/18196237/54208317-b4ee5680-44ec-11e9-8f7e-037bf140ca93.png)
And this weird part with green channel still applies:
![2019-03-12_17:32:58](https://user-images.githubusercontent.com/18196237/54208568-3c3bca00-44ed-11e9-864d-da73306e0dfd.png)
![2019-03-12_17:33:18](https://user-images.githubusercontent.com/18196237/54208555-3514bc00-44ed-11e9-8817-081a6835027f.png)

**Comment by QuentinI** [comment] 2019-03-12 14:52
When passing colors in vector format, green is still linked with transparency:
![2019-03-12_17:49:41](https://user-images.githubusercontent.com/18196237/54209855-8756dc80-44ef-11e9-9c58-9173115ce9fb.png)
![2019-03-12_17:50:26](https://user-images.githubusercontent.com/18196237/54209897-989fe900-44ef-11e9-8537-06c701b6c6b1.png)

**Comment by wacossusca34** [comment] 2019-03-12 18:07
@QuentinI the reason why transparency does not work well with bars is because the premultiply step is not included for it (and as a result, X11 will interpret the colors wrong). It's worth noting this is exclusive to `"native"` transparency.

I can fix this today.

**Comment by QuentinI** [comment] 2019-03-12 18:56
@wacossusca34 the main problem is that transparency is there in the first place. In all my screenshots I'm piping non-transparent colors into glava, but they get parsed wrong.

**Comment by wacossusca34** [comment] 2019-03-12 19:41
@QuentinI yeah, I just realized that (I read your comments too quickly).

The problem was actually my own fault, as I passed the last `vec4` element from the stdin uniform incorrectly, resulting in garbage output that somehow worked on my system. It's fixed now in `master` (I didn't reference the commit though).

As for the `circle` artifacts, that was fixed by @coderobe's commit.

This whole fiasco shows that we desperately need a test framework for GLSL, but unfortunately none seem to exist.

**Comment by wacossusca34** [comment] 2019-03-13 18:24
@QuentinI is this feature working well for you now? tag `v1.6.3` or `master` should work fine.

**Comment by QuentinI** [comment] 2019-03-13 21:07
@wacossusca34 sorry for lack of feedback, I've been unexpectedly busy. I'll check it out in a couple of hours.

**Comment by QuentinI** [comment] 2019-03-13 22:34
@wacossusca34 yeah it works as charm now. Thanks again for all the time you spent on this!

**Comment by coderobe** [comment] 2019-03-13 22:50
Glad that resolved it - would've been a pain to debug otherwise

**Comment by coderobe** [comment] 2019-03-13 22:50
Given that stdin can be used to faciliate relaying the Xdefaults colors and the surrounding issue(s) have been resolved, i've closed this for now.

**Closed by coderobe** 2019-03-13 22:50 UTC
Labels: enhancement

**Comment by wacossusca34** [comment] 2019-03-14 03:24
@QuentinI 

This feature is going to be [expanded on](https://github.com/wacossusca34/glava/pull/109#issuecomment-472688306), but will eventually replace the `--stdin` argument in favour of `--pipe` (named bindings) since new glsl syntax will be added.
