### ISSUE TITLE
Inconsistent UPS while interacting with GNOME's audio settings

### ISSUE THREAD

**Issue by ElectroCamel** [wacossusca34/glava#20] opened 2018-02-11 10:29 UTC
Right after starting glava I get 30-50 UPS, trying to find a solution I discovered that if I stop glava, switch the audio output from analog to digital or viceversa (I'm using a DAC, so they both come out of my speakers) and restart glava, I get 60 UPS, but as soon as I focus another window or close the audio settings it goes back to 40ish. I also noticed that if I change output while glava is running, it uses my USB mic as input.

Things I changed in my `rc.glsl`:

```
setinterpolate -> false
setsamplerate -> 44100
```

**Comment by wacossusca34** [comment] 2018-02-11 16:43
You should set `setsamplerate` back to `22050`. Increasing this value isn't nessecary unless your audio device has a different sample rate (**not** 44100Hz), in which case you need to select a close value that is a multiple of said sample rate.

Keep in mind GLava is just performing FFT on the audio data here, the most a higher sample rate does here is make it respond _slightly_ better to high frequencies. It also will cause lower frequencies to respond worse because of the buffer size GLava uses by default (the values get windowed, so low frequency waves may not be captured fully by the sample passed to the FFT function).

From the `rc.glsl` file's comments:
>```C
> /*                    ... It's generally OK to leave this
>   value unless you have a strange PulseAudio configuration. */
>```

> I get 60 UPS, but as soon as I focus another window or close the audio settings it goes back to 40ish.

This sounds like a process priority/affinity issue. UPS only decreases if:

* The CPU core that GLava is running literally cannot keep up with FFT computations and other transformations.
* The framerate you are running at is less than the potential UPS you could be getting. GLava notices this and automatically matches the UPS to your framerate to prevent pointless computations.

> I also noticed that if I change output while glava is running, it uses my USB mic as input.

I might be able to fix this, but I would need to play around with this scenariop myself to see what the issue is.

**Comment by wacossusca34** [comment] 2018-03-13 23:49
Closing due to insufficient information.

**Closed by wacossusca34** 2018-03-13 23:49 UTC
Labels: help wanted
