### ISSUE TITLE
'xroot' opacity broken on Mutter (GNOME, Budgie desktop)

### ISSUE THREAD

**Issue by kartik-bhagatwala** [wacossusca34/glava#18] opened 2018-02-08 02:25 UTC
Opacity does not work on my Ubuntu 16.04 setup running GNOME on an x11 system. In my radial.glsl:
`#request setopacity "xroot"`, yet this does not work and the black background is still seen.

**Comment by wacossusca34** [comment] 2018-02-08 03:57
In case this is related to #11, can you do what I asked in that issue:

> Can you paste the output of running `xprop` and `xwininfo `in a terminal and clicking your desktop background?

Also, make sure GLava's window isn't overlapping on two (or more) monitors and that you have `libxext` installed.

**Comment by kartik-bhagatwala** [comment] 2018-02-08 05:19
yes, `libxext-dev` is installed.

```
xprop
WM_NAME(STRING) = "mutter guard window"
```
```
xwininfo: Window id: 0x140001b "mutter guard window"

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1920
  Height: 1080
  Depth: 0
  Visual: 0x20
  Visual Class: TrueColor
  Border width: 0
  Class: InputOnly
  Colormap: 0x0 (not installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +0+0  -0+0  -0-0  +0-0
  -geometry 1920x1080+0+0

```

**Comment by wacossusca34** [comment] 2018-02-08 05:39
Looks like GNOME creates some sort of 'gaurd window' on top of the desktop to hide windows behind, in order to create preview windows (?). If the desktop is actually being drawn to this window instead of the root window, I can add a GNOME-specific fix, and there's [even a bug fix](https://mail.gnome.org/archives/commits-list/2013-October/msg05926.html) for the WM giving it the `"mutter gaurd window"` title so applications can filter/identify it.

But on the other hand, documentation indicates that backgrounds are drawn on the root X window: https://developer.gnome.org/meta/stable/MetaBackgroundActor.html

> ```C
> struct MetaBackgroundActor;
> ```
> This class handles tracking and painting the root window background. By integrating with MetaWindowGroup we can avoid painting parts of the background that are obscured by other windows.

I need to get my hands on a Mutter (GNOME) WM to see what is really going on here.

**Comment by wacossusca34** [comment] 2018-02-09 01:15
From related issue #11:

> I'm still toying around with this, but if you have time please test the `unstable` branch as the above commit may have fixed the issue.

**Comment by wacossusca34** [comment] 2018-02-09 04:27
I have confirmed the issue myself running gnome (on Xephyr under a `systemd-nspawn` Arch container) with `"xroot"` style transparency. The above fix does not work, and applies to all desktop environments using mutter (gnome, budgie desktop), making this the same as issue #11 

As a temporary fix, you can set the same wallpaper on the root X window using a tool like `feh` or something similar on GNOME and Budige (using `master`, don't use `unstable`). Make sure the wallpapered is positioned and transformed the same way as the wallpaper on Mutter. `"native"` transparency also works, but you will need GLFW 3.3 (and alpha blending will not work, so that is not a viable solution either).

I will investigate a solution using Xcomposite to capture other window contents for mutter-based WMs.

**Comment by wacossusca34** [comment] 2018-02-09 05:25
Here is a demonstration of the workaround using `feh --bg-fill ~/wallpaper.png`, and then selecting the same wallpaper with `gnome-control-center` with GNOME running in the top right window:

<img src="https://i.imgur.com/Garap54.png" />

GLava is using `"xroot"` style transparency and defaults for everyting else.

**Comment by Riokei** [comment] 2018-02-09 18:39
Okay so I tried feh but 
![screenshot from 2018-02-09 13 38 56](https://user-images.githubusercontent.com/16841390/36043819-991f2636-0d9e-11e8-8917-7f30a5f9d469.png)
is there anyway to make that window shadow go away?

**Comment by wacossusca34** [comment] 2018-02-10 00:14
@Riokei For compton, you can add `"window_type = 'desktop'"` to the `shadow-exclude` variable in your `.config/comtpon.conf` file.

If mutter is drawing these, there currently is no good way to disable window shadows for particular windows. See [this answer regarding mutter configuration options](https://askubuntu.com/a/96744). You can try disabling shadows completely by adding `.window-frame {box-shadow: none;}` to `~/.config/gtk-3.0/gtk.css` (or the relevant theme).

Another solution would be to use a GLava window large enough to obscure the shadow (ie. 1920x1080). I could also look at adding a solution where GLava uses a fullscreen desktop window, but only renders to a portion of it, too.

**Comment by wacossusca34** [comment] 2018-02-10 00:25
A comment on Mutter itself: this WM is a prime example of how GNOME developers shoot themselves in the foot. A lack of configuration options and behaving in non-standard ways (ie. not drawing to the background pixbuf of the root window) just causes headaches for developers and users.

I may abandon this issue in favour of `"native"` transparency if I can get alpha blending working for it (perhaps I can implement it myself instead of letting GLFW handle it).

**Comment by Riokei** [comment] 2018-02-11 14:50
I'll use it fullscreen til GLFW is updated on Solus and I can use native transparency. Thanks for the help!

**Comment by wacossusca34** [comment] 2018-02-12 01:41
Another update, I am working on making `"native"` transparency work without GLFW at all (using GLX directly instead) and will fix alpha blending with it since [I ruled that out to be a quirk with X11 compositors](https://github.com/glfw/glfw/issues/1211). As a result, I will close this issue with `wonfix` since `"native"` transparency will be the new default.

**Comment by wacossusca34** [comment] 2018-02-13 00:56
GLava 1.4 has been released, which has much better support for `"native"` transparency. It's now the default for GLava instead of `"xroot"`, and since there is no easy solution to get `"xroot"` working on Mutter, I'm closing this in favour of using the new transparency support.

You no longer need GLFW 3.3 for transparency support, either. It is provided in the new GLX backend, which should automatically work unless you're actually running under an XWayland session.

Demonstration of the new `"native"` transparency under GNOME:

<img src="https://i.imgur.com/vp3qO9v.png" />

**Closed by wacossusca34** 2018-02-13 00:56 UTC
Labels: WM compatibility

**Comment by wacossusca34** [comment] 2018-02-13 01:16
Oh, and @Riokei `"native"` transparency when decorations are disabled seems to cause window shadows to disappear on Mutter, so you no longer need to use `feh` or the fullscreen workaround.
