### ISSUE TITLE
Memory leak after extended use

### ISSUE THREAD

**Issue by zaza42** [wacossusca34/glava#33] opened 2018-03-12 15:43 UTC
I'm running glava for 7 days and it's ram usage is growing constantly.
1 hour ago (psmem):
`282.8 MiB +   7.5 MiB = 290.3 MiB       glava`
then:
`286.4 MiB +   7.5 MiB = 293.9 MiB       glava`
then:
`289.6 MiB +   7.5 MiB = 297.1 MiB       glava`
[pmap_-x_glava.txt](https://github.com/wacossusca34/glava/files/1803450/pmap_-x_glava.txt)
[glava-status.txt](https://github.com/wacossusca34/glava/files/1803451/glava-status.txt)

**Comment by Aaahh** [comment] 2018-03-12 16:04
Do you have Nvidia prime?

**Comment by zaza42** [comment] 2018-03-12 16:09
`01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Seymour [Radeon HD 6400M/7400M Series]` with the opensource radeon driver.

**Comment by wacossusca34** [comment] 2018-03-12 23:23
I have, admittedly, encountered leaks as well. They seem to be more severe on the nvidia driver.

Unfortunately it's something to do with resources associated with the OpenGL context, rather than memory I am allocating in GLava itself. In fact, GLava does not even allocate heap memory once everything is initialized, the rendering loop just functions off of existing heap or stack.

If someone can try to dig around and see what I could possibly doing wrong with regards to OpenGL calls, that would be a big help -- otherwise I will put this on my growing todo list.

**Comment by wacossusca34** [comment] 2018-03-19 04:11
This is fairly hard to test. I did notice on a very old GLava build using `"xroot"` transparency that there was a massive growth in shared memory used, but I have since fixed the XShm code that was causing _that_ issue.

To compare, I grabbed `ps_mem.py` (tool that @zaza42 is using for readable memory usage output) and looked at what was being reported for a new GLava instance:

```
~/C/GLava$ python ~/ps_mem.py -p 6901
 Private  +   Shared  =  RAM used	Program

 28.4 MiB +   7.4 MiB =  35.7 MiB	glava
...
```

So, it looks like the memory usage @zaza42 is encountering is actually absurd. The problem is that I'm not leaking the memory directly with `malloc`:

```
~/C/GLava$ grep malloc -n *.c
glava.c:39:        char* buf = malloc(PATH_MAX);           \
glsl_ext.c:174:                    void** processed_args = malloc(strlen(handler->fmt) * sizeof(void*));
glsl_ext.c:189:                                processed_args[i] = malloc(sizeof(int));
glsl_ext.c:196:                                processed_args[i] = malloc(sizeof(float));
glsl_ext.c:222:                                processed_args[i] = malloc(sizeof(bool));
glsl_ext.c:262:        .buf   = malloc(256),
glsl_ext.c:421:                            args = malloc(sizeof(char*));
glsl_ext.c:439:                        args[args_sz - 1] = malloc((end - arg_start_idx) + 1); \
glx_wcb.c:84:    struct glxwin* w = malloc(sizeof(struct glxwin));
pulse_input.c:20:	audio->source = malloc(sizeof(char) * 1024);
render.c:185:    GLchar* buf = malloc((blen * sizeof(GLchar*)) + ext.p_len);
render.c:469:        u = malloc(sizeof(*u));                 \
render.c:685:    renderer* r = malloc(sizeof(struct renderer));
render.c:688:        .gl                   = malloc(sizeof(struct gl_data)),
render.c:787:    char** xwinstates = malloc(1);
render.c:848:                        char* str = malloc(sizeof(char) * (strlen((char*) args[0]) + 1));
render.c:1010:                        .transformations = malloc(1),
render.c:1140:            stages = malloc(sizeof(struct gl_sfbo) * count);
render.c:1159:                                .binds      = malloc(1),
render.c:1239:        float* ibuf = malloc(isz * 6 * sizeof(float));
render.c:1250:        gl->t_data = malloc(sizeof(void*) * t_count);
render.c:1477:                        sm = malloc(sizeof(struct sm_fb));
xwin.c:244:            buf = malloc(4 * w * h);
```

In _all_ of these use cases, the memory is either allocated during initialization, or as needed (but only once) during rendering (ie. the the `ALLOC_ONCE` macro in `render.c`). Memory that is not needed after initialization is appropriately `free`'d, and any remaining heap memory shouldn't grow but will remain in use for the lifetime of the program.

So this is clearly a more complex resource leak through either OpenGL or PulseAudio (and I find it unlikely to be the latter).

**Comment by wacossusca34** [comment] 2018-03-19 05:04
I did stumble upon a leak in `xwin_should_render`, since it used to rely on closing the display to cleanup resources before I fixed #15 (which was ironically also reported by you)

Not sure if this is the actual resource leak causing the reported issue, but it's a start. I'm heading off to sleep and will test this more later.

**Comment by Aaahh** [comment] 2018-03-19 08:02
heaptrack stats:
	allocations:          	11802410
	leaked allocations:   	1361517
	temporary allocations:	1178956


Well I started running that before your commit thought...

**Comment by wacossusca34** [comment] 2018-03-19 13:22
@Aaahh you'll definately want to try with the most recent fix in `master`. It was responsible for a lot of small allocations being leaked.

**Comment by zaza42** [comment] 2018-03-20 12:52
Ok, i'm runnig glava for 12 hours now, and it's still using 
` 17.8 MiB +  10.0 MiB =  27.8 MiB	glava
`
I'll report again some days later.

**Comment by wacossusca34** [comment] 2018-03-20 13:37
I'll test this some more later today and then close it if I don't encounter any serious memory fluctuations.

**Comment by Aaahh** [comment] 2018-03-20 19:36
heaptrack stats:
	allocations:          	28125699
	leaked allocations:   	2773
	temporary allocations:	3174705
Major improvement

**Comment by wacossusca34** [comment] 2018-03-20 23:20
> [...] ALLOC_ONCE is leaking everywhere its used (50kBs a piece, so honestly eh)
> render.c:534,
> render.c:558

Are you sure? Is it only leaking 50kB for each expansion of this macro or for each _invocation_? If it's the former, I'm pretty sure it's not actually a leak (pointers to the data are kept in `void** udata` arguments to the transform functions). For reference, here is the definition of `ALLOC_ONCE`:

```C
#define ALLOC_ONCE(u, udata, ...)                \
    if (*udata == NULL) {                       \
        u = malloc(sizeof(*u));                 \
        *u = (typeof(*u)) __VA_ARGS__;          \
        *udata = u;                             \
    } else u = (typeof(u)) *udata;
```

This is a type-generic macro where `u` is an lvalue of a pointer to any type, and `udata` is a `void**` pointer storing a copy of the aforementioned pointer to use for later invocations.

**Comment by Aaahh** [comment] 2018-03-20 23:40
Heaptracker is reporting 100kB leak in total over the course of the program at those lines
I could send you the data, there’s minor memory leaks in rd and I could narrow it down to that line 
I didn’t spend much time after, it’s so minute I wouldn’t worry about it

**Comment by wacossusca34** [comment] 2018-03-20 23:48
@Aaahh that sounds like heaptracker is just failing to find where the data associated with `ALLOC_ONCE` calls remains after `malloc` invocations. It's permenently stored in `gl->t_data[n]` (`void**` array that _also_ resides in the heap), but isn't first allocated to that location.

It's not particularily easy to determine whether data is _definately_ being leaked by the program, hence why software like `valgrind` is so vague when describing the nature of leaks.

**Comment by wacossusca34** [comment] 2018-03-20 23:50
Closing this issue since it appears the serious leak that was hogging system memory before is gone.

**Closed by wacossusca34** 2018-03-20 23:50 UTC
Labels: bug, help wanted

**Comment by wacossusca34** [comment] 2018-03-20 23:55
@Aaahh if you return on IRC I can discuss ironing out the remaining smaller leaks (I recieved your messages earlier today, but your client appears to be offline).

**Comment by zaza42** [comment] 2018-03-21 14:05
after one day:
`  7.9 MiB +   3.1 MiB =  10.9 MiB	glava
`
I think it's ok now.
